server:
  port: ${API_GATEWAY_PORT:9090}
  
zuul :
  host:
    socket-timeout-millis : 20000
    connect-timeout-millis : 20000
    connection-request-timeout-millis : 60000
    max-per-route-connections : 10000
    max-total-connections : 5000
  ignoredServices: '*'
  routes :
    auth-service:
      path : /api/auth/**
      serviceId : auth-service
      stripPrefix: false
      sensitive-headers: Cookie,Set-Cookie
    post-service:
      path: /api/content/**
      serviceId : post-service
      stripPrefix: false
      sensitive-headers : Cookie,Set-Cookie
    user-service :
      path : /api/users/**
      serviceId : user-service
      stripPrefix: false
      sensitive-headers : Cookie,Set-Cookie
    user-graph-service :
      path : /api/user-graph/**
      serviceId : user-graph-service
      stripPrefix: false
      sensitive-headers : Cookie,Set-Cookie
    feed-service:
      path : /api/feed/**
      serviceId: feed-service
      stripPrefix: false
      sensitive-headers: Cookie,Set-Cookie
  ribbon :
    eager-load :
      enabled : true

ribbon:
  ConnectTimeout: 10000
  ReadTimeout: 10000

hystrix:
  command:
    default:
      execution:
        timeout:
          enabled: false

auth-service:
  ribbon:
    listOfServers: auth-service:${AUTH_SERVICE_PORT}

post-service:
  ribbon:
    listOfServers: post-service:${POST_SERVICE_PORT}

user-service:
  ribbon:
    listOfServers: user-service:${USER_SERVICE_PORT}

user-graph-service:
  ribbon:
    listOfServers: user-graph-service:${USER_GRAPH_SERVICE_PORT}

feed-service:
  ribbon:
    listOfServers: feed-service:${FEED_SERVICE_PORT}


nistagram.security.jwt.secret: ${JWT_SECRET:test_secret}

