server :
  port : ${API_GATEWAY_PORT:9090}

spring :
  application :
    name : spring-nistagram-api-gateway

opentracing :
  jaeger :
    http-sender :
      url : http://jaeger:14268/api/traces

zuul :
  host :
    socket-timeout-millis : 20000
    connect-timeout-millis : 20000
    connection-request-timeout-millis : 60000
    max-per-route-connections : 10000
    max-total-connections : 5000
  ignoredServices : '*'

  routes :
    auth-service :
      path : /api/auth/**
      serviceId : auth-service
      stripPrefix : false
      sensitive-headers : Cookie,Set-Cookie
    post-service :
      path : /api/content/**
      serviceId : post-service
      stripPrefix : false
      sensitive-headers : Cookie,Set-Cookie
    user-service :
      path : /api/users/**
      serviceId : user-service
      stripPrefix : false
      sensitive-headers : Cookie,Set-Cookie
    user-graph-service :
      path : /api/user-graph/**
      serviceId : user-graph-service
      stripPrefix : false
      sensitive-headers : Cookie,Set-Cookie
    feed-service :
      path : /api/feed/**
      serviceId : feed-service
      stripPrefix : false
      sensitive-headers : Cookie,Set-Cookie
    notification-service :
      path : /api/notification/**
      serviceId : notification-service
      stripPrefix : false
      customSensitiveHeaders : true
      sensitive-headers : Cookie,Set-Cookie
    chat-service :
      path : /api/chat/**
      serviceId : chat-service
      stripPrefix : false
      customSensitiveHeaders : true
      sensitive-headers : Cookie,Set-Cookie
    campaign-service :
      path : /api/campaigns/**
      serviceId : campaign-service
      stripPrefix : false
      sensitive-headers : Cookie,Set-Cookie
  ws :
    brokerages :
      notification-service :
        end-points : /api/notification/ws
        brokers : /queue
  ribbon :
    eager-load :
      enabled : true

ribbon :
  ConnectTimeout : 10000
  ReadTimeout : 10000

hystrix :
  command :
    default :
      execution :
        timeout :
          enabled : false

auth-service :
  ribbon :
    listOfServers : auth-service:${AUTH_SERVICE_PORT}

post-service :
  ribbon :
    listOfServers : post-service:${POST_SERVICE_PORT}

user-service :
  ribbon :
    listOfServers : user-service:${USER_SERVICE_PORT}

user-graph-service :
  ribbon :
    listOfServers : user-graph-service:${USER_GRAPH_SERVICE_PORT}

feed-service :
  ribbon :
    listOfServers : feed-service:${FEED_SERVICE_PORT}

notification-service :
  ribbon :
    listOfServers : notification-service:${NOTIFICATION_SERVICE_PORT}

chat-service :
  ribbon :
    listOfServers : chat-service:${CHAT_SERVICE_PORT}

campaign-service :
  ribbon :
    listOfServers : campaign-service:${CAMPAIGN_SERVICE_PORT}


nistagram.security.jwt.secret : ${JWT_SECRET:test_secret}

nistagram.headers.agent : agent
nistagram.headers.app : app
nistagram.headers.user : username


