server:
  port: ${API_GATEWAY_PORT:9090}
  ssl:
    enabled: true
    key-store-type: PKCS12
    key-store: keystores/nistagram-keystore.p12
    key-password: ${KEY_PASSWORD}
    key-alias: ${CERTIFICATE_ALIAS}
    key-store-password: ${KEYSTORE_PASSWORD}

zuul :
  ignoredServices: '*'
  routes :
    auth-service:
      path : /api/auth/**
      serviceId : auth-service
      stripPrefix: false
      sensitive-headers: Cookie,Set-Cookie
    post-service:
      path: /api/content/**
      serviceId : post-service
      stripPrefix: false
      sensitive-headers : Cookie,Set-Cookie
    user-service :
      path : /api/users/**
      serviceId : user-service
      stripPrefix: false
      sensitive-headers : Cookie,Set-Cookie
    user-graph-service :
      path : /api/user-graph/**
      serviceId : user-graph-service
      stripPrefix: false
      sensitive-headers : Cookie,Set-Cookie
    feed-service:
      path : /api/feed/**
      serviceId: feed-service
      stripPrefix: false
      sensitive-headers: Cookie,Set-Cookie

ribbon:
  eureka:
    enabled: false
    ReadTimeout : 100000
    ConnectTimeout : 100000

hystrix:
  command:
    default:
      execution:
        timeout:
          enabled: false

auth-service:
  ribbon:
    listOfServers: auth-service:${AUTH_SERVICE_PORT}

post-service:
  ribbon:
    listOfServers: post-service:${POST_SERVICE_PORT}

user-service:
  ribbon:
    listOfServers: user-service:${USER_SERVICE_PORT}

user-graph-service:
  ribbon:
    listOfServers: user-graph-service:${USER_GRAPH_SERVICE_PORT}

feed-service:
  ribbon:
    listOfServers: feed-service:${FEED_SERVICE_PORT}


nistagram.security.jwt.secret: ${JWT_SECRET:test_secret}

